AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Simple lambda testing Locale resources 
Resources:
  AlexaLocaleStreamHandler:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java8
      Handler: kjd.alexa.locale::AlexaLocaleStreamHandler